config/routes.rb
RunningLog::Application.routes.draw do
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    resources :workouts, only: [:create, :destroy]

    root to: 'home_and_info_pages#home'
    
    match '/signup',  to: 'users#new'
    match '/signin',  to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete
    
    match '/help',    to: 'home_and_info_pages#help'
    match '/about',   to: 'home_and_info_pages#about'
    match '/contact', to: 'home_and_info_pages#contact'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :workouts

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  attr_accessible :workout_date, :distance, :effort, :emotion, :name, :review, :weather, :duration
  belongs_to :user

  validates :distance, presence: true 
  validates :duration, presence: true 

  def self.total_miles_on(date, id)
    where("date(workout_date) = ?",date).where("user_id="+id.to_s).sum(:distance)
  end

  def self.total_duration_on(date, id)
    where("date(workout_date) = ?",date).where("user_id="+id.to_s).sum(:duration)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/home_and_info_pages_controller.rb
class HomeAndInfoPagesController < ApplicationController
  def home
  	if signed_in?
      redirect_to current_user
    end
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'home_and_info_pages/home'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Running Log!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def update
    #if @user.update_attributes(params[:user])
    #  flash[:success] = "Profile updated"
    #  sign_in @user
    #  redirect_to @user
    #else
    #  render 'edit'
    #end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def show
    @user = User.find(params[:id])
    @workouts  = Workout.where("user_id="+params[:id])
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
  end

  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
        redirect_to(root_path) unless current_user.admin?
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user,   only: :destroy

  def create
    @workout = current_user.workouts.build(params[:workout])
    if @workout.save
      flash[:success] = "Workout logged!"
      respond_to do |format|
        format.html {redirect_to root_url}
        format.js
      end
    else
      @feed_items = []
      render 'home_and_info_pages/home'
    end
  end

  def destroy
    @workout.destroy
    redirect_to root_url(:pflag => params[:pflag])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Running Log"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/home_and_info_pages_helper.rb
module HomeAndInfoPagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/home_and_info_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About us</h1>
<p>We are the greatest people on Earth. That's all you really have to know.</p>

app/views/home_and_info_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  A yo, call me girl
</p>

app/views/home_and_info_pages/help.html.erb
  	<% provide(:title, 'About Us') %>
    <h1>Help</h1>
    <p>
    	You click on the things and the screen changes.
    </p>

app/views/home_and_info_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="wrapper">
	<div id="bg">
		<img src="assets/login_bg1.jpg" alt="">
	</div>
	<div class="welcome">
		<h1>Welcome to Running Log</h1>
		<p class="textbox">
		  Set your goals, log your runs, veiw your progress, and share it all with people you care about.
		</p>
	</div>
	<div class="signin">
		<h3>Sign in</h3>
	    <%= form_for(:session, url: sessions_path) do |f| %>
	      <%= f.label :email %>
	      <%= f.text_field :email %>

	      <%= f.label :password %>
	      <%= f.password_field :password %>

	      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
	    <% end %>

	    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Running log by Ben Schmaltz - <a href="https://github.com/bschmaltz/running_log" target="blank">source code</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "running log", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", root_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "jquery-2.1.3.min", "bootstrap.min", "main", "highcharts" %>




    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
 <%= feed_item.name %>
</li>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/shared/graph_data.html.erb
<%= hidden_field_tag :yolo, ((7.days.ago.to_date..Date.today).map { |date| Workout.total_miles_on(date, params[:id]).to_f}.inspect), :id => 'weekly_distance' %>
  <%= hidden_field_tag :yolo, ((7.days.ago.to_date..Date.today).map { |date| Workout.total_duration_on(date, params[:id]).to_f}.inspect), :id => 'weekly_duration' %>
  <%= hidden_field_tag :yolo, ((1.month.ago.to_date..Date.today).map { |date| Workout.total_miles_on(date, params[:id]).to_f}.inspect), :id => 'monthly_distance' %>
  <%= hidden_field_tag :yolo, ((1.month.ago.to_date..Date.today).map { |date| Workout.total_duration_on(date, params[:id]).to_f}.inspect), :id => 'monthly_duration' %>
  <%= hidden_field_tag :yololo, params[:id], :id => 'user_id_field' %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/data.html.erb
<%= hidden_field_tag :yolo, ((7.days.ago.to_date..Date.today).map { |date| Workout.total_miles_on(date, params[:id]).to_f}.inspect), :id => 'weekly_distance' %>
  <%= hidden_field_tag :yolo, ((7.days.ago.to_date..Date.today).map { |date| Workout.total_duration_on(date, params[:id]).to_f}.inspect), :id => 'weekly_duration' %>
  <%= hidden_field_tag :yolo, ((1.month.ago.to_date..Date.today).map { |date| Workout.total_miles_on(date, params[:id]).to_f}.inspect), :id => 'monthly_distance' %>
  <%= hidden_field_tag :yolo, ((1.month.ago.to_date..Date.today).map { |date| Workout.total_duration_on(date, params[:id]).to_f}.inspect), :id => 'monthly_duration' %>
  <%= hidden_field_tag :yololo, params[:id], :id => 'user_id_field' %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/graph_data.html.erb
<%= hidden_field_tag :yolo, ((7.days.ago.to_date..Date.today).map { |date| Workout.total_miles_on(date, params[:id]).to_f}.inspect), :id => 'weekly_distance' %>
  <%= hidden_field_tag :yolo, ((7.days.ago.to_date..Date.today).map { |date| Workout.total_duration_on(date, params[:id]).to_f}.inspect), :id => 'weekly_duration' %>
  <%= hidden_field_tag :yolo, ((1.month.ago.to_date..Date.today).map { |date| Workout.total_miles_on(date, params[:id]).to_f}.inspect), :id => 'monthly_distance' %>
  <%= hidden_field_tag :yolo, ((1.month.ago.to_date..Date.today).map { |date| Workout.total_duration_on(date, params[:id]).to_f}.inspect), :id => 'monthly_duration' %>
  <%= hidden_field_tag :yololo, params[:id], :id => 'user_id_field' %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

  <div id="bg">
    <img src="assets/login_bg1.jpg" alt="">
  </div>
<div id="signup_form">
  <h1 class="center_header">Sign up</h1>
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>
        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
      <% end %>
</div>

app/views/users/show.html.erb
<div id="user_info">
	<div id="username"><%= @user.name %></div>
	<div id="userpic"><%= gravatar_for @user %></div>
<% if(current_user?(@user)) %>
	<a role="button" class="btn btn-info" data-toggle="modal" data-target="#myModal" id="log_btn">LOG A WORKOUT</a>
	<div class="workout_form">
		<%= simple_form_for Workout.new, :id => 'new_workout' do |f| %>
	 	<%= render 'shared/error_messages', object: f.object %>

		<!-- Modal -->
		<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-header">
		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		    <h3 id="myModalLabel">New Log Entry</h3>
		  </div>
	  	<div class="modal-body">
			  <div class="workout_inputs">
			    <%= f.input :name, placeholder: "Workout name..." %>

			    <%= f.input :workout_date, :start_year => 1940 %>

				  <%= f.input :duration, placeholder: "(minutes)", id: "duration_field" %><span id="duration_field_error"></span>

			    <%= f.input :distance, placeholder: "(miles)", id: "distance_field" %><span id="distance_field_error"></span>

			    <%= f.label :effort, id: "effort_label" %><text id="effort_value">3</text>
			    <%= f.range_field :effort, :min=>1, :max=>5, :class=>"slide", :id=>"slider1"%>

			    <%= f.label "Weather" %>
			    <div id="weather_icons">
				<%= f.collection_radio_buttons(:weather, [["Sunny", "icon_sunny_grey"], ["Cloudy", "icon_cloudy_grey"], ["Rainy", "icon_rainy_grey"], ["Stormy", "icon_stormy_grey"]],
                             :first, :last,
                             :item_wrapper_class => 'weather_icon',
                             ) { |weather| weather.label { image_tag("/assets/icons/#{weather.text}.png") + weather.radio_button } }%>
                </div>

			    <%= f.label :review %>
			    <%= f.text_area :review, placeholder: "How did it go?" %>
			    
			  </div>
			</div>
			<div class="modal-footer">
		    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		    <%= f.submit "Log it!", class: "btn btn-large btn-primary", id: "submit_log_btn" %>
		  </div>
		</div>
		<% end %>
	</div>
<% end %>
</div>
<div id="graph_data">
  <%= hidden_field_tag :yolo, ((7.days.ago.to_date..Date.today).map { |date| Workout.total_miles_on(date, params[:id]).to_f}.inspect), :id => 'weekly_distance' %>
  <%= hidden_field_tag :yolo, ((7.days.ago.to_date..Date.today).map { |date| Workout.total_duration_on(date, params[:id]).to_f}.inspect), :id => 'weekly_duration' %>
  <%= hidden_field_tag :yolo, ((1.month.ago.to_date..Date.today).map { |date| Workout.total_miles_on(date, params[:id]).to_f}.inspect), :id => 'monthly_distance' %>
  <%= hidden_field_tag :yolo, ((1.month.ago.to_date..Date.today).map { |date| Workout.total_duration_on(date, params[:id]).to_f}.inspect), :id => 'monthly_duration' %>
  <%= hidden_field_tag :yololo, params[:id], :id => 'user_id_field' %>
</div>

<div id="calendar">
  <h2 id="month">
    <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m") %>
    <%=h @date.strftime("%B %Y") %>
    <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m") %>
  </h2>
  <%= calendar_for @workouts, :year => @date.year, :month => @date.month do |calendar| %>
    <%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') %>
    <% calendar.day(:day_method => :workout_date) do |date, workouts| %>
      <%= date.day %>
      <ul>
        <% for workout in workouts %>
          <li>
          </li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>


<h2>Weekly Summary</h2>
<div class="accordion" id="accordion1">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#weekly_distance_panel">
        Distance
      </a>
    </div>
    <div id="weekly_distance_panel" class="accordion-body collapse in">
      <div class="accordion-inner">
        <div class="graph" id="weekly_distance_graph"></div>
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#weekly_pace_panel">
        Pace
      </a>
    </div>
    <div id="weekly_pace_panel" class="accordion-body collapse">
      <div class="accordion-inner">
        <div class="graph" id="weekly_pace_graph"></div>
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#weekly_speed_panel">
        Speed
      </a>
    </div>
    <div id="weekly_speed_panel" class="accordion-body collapse">
      <div class="accordion-inner">
        <div class="graph" id="weekly_speed_graph"></div>
      </div>
    </div>
  </div>
</div>

<h2>Monthly Summary</h2>
<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Distance
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse in">
      <div class="accordion-inner">
        <div class="graph" id="monthly_distance_graph"></div>
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
        Pace
      </a>
    </div>
    <div id="collapseTwo" class="accordion-body collapse">
      <div class="accordion-inner">
        <div class="graph" id="monthly_pace_graph"></div>
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
        Speed
      </a>
    </div>
    <div id="collapseThree" class="accordion-body collapse">
      <div class="accordion-inner">
        <div class="graph" id="monthly_speed_graph"></div>
      </div>
    </div>
  </div>
</div>

app/views/workouts/create.js.erb
$(".graph").fadeOut(400, function() {
	
	$(this).fadeIn(2000);
});

app/views/workouts/new.html.erb
<h1>Workouts#new</h1>
<p>Find me in app/views/workouts/new.html.erb</p>